server:
  port: 8080
spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
        listener:
          max-messages: 10
          poll-timeout: 10s
          visibility-timeout: 30s
  application:
    name: policy-service
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false
policy:
  fraud:
    base-url: http://localhost:8089/v1
feign:
  client:
    config:
      fraudClient:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic
logging:
  level:
    com.acme.insurance.policy.infra.fraud: DEBUG
    feign: INFO
aws:
  region: us-east-1
  dynamodb:
    endpoint: http://localhost:4566
    table: PolicyRequests