version: '3.9'
services:
  localstack:
    image: localstack/localstack:3.7
    environment:
      - SERVICES=dynamodb,sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - "4566:4566"
    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"
    networks:
      - app-net

  wiremock:
    image: wiremock/wiremock:3.9.1
    command: ["--verbose","--global-response-templating"]
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    ports: ["8089:8080"]
    networks:
      - app-net

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: acme-insurance
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - SQS_ENDPOINT=http://localstack:4566
      - FRAUD_API_URL=http://wiremock:8080
      - SERVER_PORT=8080
      - OTEL_SERVICE_NAME=policy-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_SAMPLER=parentbased_always_on
      - OTEL_LOGS_EXPORTER=none
      - OTEL_INSTRUMENTATION_COMMON_PEER_SERVICE_MAPPING=wiremock:8080=fraud-api,localstack:4566=aws-localstack
      - OTEL_RESOURCE_ATTRIBUTES=service.version=0.1.0,env=dev
    depends_on:
      - localstack
      - wiremock
      - otel-collector
    networks:
      - app-net

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - app-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ../observability/otel-collector.yaml:/etc/otel-collector.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
    networks:
      - app-net

networks:
  app-net:
    driver: bridge