version: '3.9'
services:
  localstack:
    image: localstack/localstack:3.7
    environment:
      - SERVICES=dynamodb,sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - "4566:4566"
    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"
    networks:
      - app-net
  wiremock:
    image: wiremock/wiremock:3.9.1
    command: ["--verbose","--global-response-templating"]
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    ports: ["8089:8080"]
    networks:
      - app-net
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: acme-insurance
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - SQS_ENDPOINT=http://localstack:4566
      - FRAUD_API_URL=http://wiremock:8080
      - SERVER_PORT=8080
    depends_on:
      - localstack
      - wiremock
    networks:
      - app-net

networks:
  app-net:
    driver: bridge